channels:
- conda-forge
dependencies:
- python=3.8.20
- pip<=24.2
- pip:
  - mlflow==2.17.0
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - psutil==6.1.0
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
